balloon_gas_particle             ="minecraft:balloon_gas_particle             "  # -圆形白色粒子（潜影贝子弹尾迹）
basic_crit_particle              ="minecraft:basic_crit_particle              "  # -暴击粒子
basic_flame_particle             ="minecraft:basic_flame_particle             "  # -小型火焰🔥子
basic_portal_particle            ="minecraft:basic_portal_particle            "  # -传送门粒子
basic_smoke_particle             ="minecraft:basic_smoke_particle             "  # -向上烟雾粒子
bleach                           ="minecraft:bleach                           "  # -村民愤怒粒子
bubble_column_bubble             ="minecraft:bubble_column_bubble             "  # -白色气泡粒子(需要在水中才能显示)
bubble_column_down_particle      ="minecraft:bubble_column_down_particle      "  # -向下气泡粒子(需要在水中才能显示)
bubble_column_up_particle        ="minecraft:bubble_column_up_particle        "  # -向上气泡粒子(需要在水中才能显示)
basic_bubble_particle_manual     ="minecraft:basic_bubble_particle_manual     "  # -气泡粒子(需要在水中才能显示)
camera_shoot_explosion           ="minecraft:camera_shoot_explosion           "  # -相机爆炸粒子
campfire_smoke_particle          ="minecraft:campfire_smoke_particle          "  # -营火粒子(短)
campfire_tall_smoke_particle     ="minecraft:campfire_tall_smoke_particle     "  # -营火粒子(长)
cauldron_bubble_particle         ="minecraft:cauldron_bubble_particle         "  # -气泡粒子2(需要在水中才能显示)
cauldron_splash_particle         ="minecraft:cauldron_splash_particle         "  # -黑色颗粒(需要在水中才能显示)
conduit_particle                 ="minecraft:conduit_particle                 "  # -潮涌能量粒子(无法正常显示)
conduit_attack_emitter           ="minecraft:conduit_attack_emitter           "  # -潮涌核心粒子(无法正常显示)
critical_hit_emitter             ="minecraft:critical_hit_emitter             "  # -大型暴击粒子
dolphin_move_particle            ="minecraft:dolphin_move_particle            "  # -气泡粒子3(需要在水中才能显示)
dragon_breath_fire               ="minecraft:dragon_breath_fire               "  # -向上龙息粒子
dragon_breath_lingering          ="minecraft:dragon_breath_lingering          "  # -向上龙息粒子(稍大)
dragon_breath_trail              ="minecraft:dragon_breath_trail              "  # -龙息粒子(末影龙火球粒子)
dragon_death_explosion_emitter   ="minecraft:dragon_death_explosion_emitter   "  # -末影龙死亡爆炸粒子
dragon_destroy_block             ="minecraft:dragon_destroy_block             "  # -末影龙破坏方块粒子
dragon_dying_explosion           ="minecraft:dragon_dying_explosion           "  # -龙死前爆炸？粒子
enchanting_table_particle        ="minecraft:enchanting_table_particle        "  # -附魔台符文粒子
lava_drip_particle               ="minecraft:lava_drip_particle               "  # -岩浆滴落粒子
mobflame_emitter                 ="minecraft:mobflame_emitter                 "  # -一束火焰🔥(必须退出存档才能清除)
end_chest                        ="minecraft:end_chest                        "  # -末影箱粒子
basic_bubble_particle            ="minecraft:basic_bubble_particle            "  # -通用气泡粒子
evocation_fang_particle          ="minecraft:evocation_fang_particle          "  # -幻魔者尖牙粒子（向下）
evoker_spell                     ="minecraft:evoker_spell                     "  # -长时间黑色气泡
cauldron_explosion_emitter       ="minecraft:cauldron_explosion_emitter       "  # -白色烟雾粒子
egg_destroy_emitter              ="minecraft:egg_destroy_emitter              "  # -鸡蛋碎裂？粒子
eyeofender_death_explode_particle="minecraft:eyeofender_death_explode_particle"  # -末影之眼碎裂粒子
misc_fire_vapor_particle         ="minecraft:misc_fire_vapor_particle         "  # -蒸汽发生器？粒子
explosion_particle               ="minecraft:explosion_particle               "  # -爆炸粒子(其实就是小型烟雾)
fish_hook_particle               ="minecraft:fish_hook_particle               "  # -鱼钩粒子(需要在水中才能显示)
fish_pos_particle                ="minecraft:fish_pos_particle                "  # -气泡粒子4 (需要在水中才能显示)
guardian_attack_particle         ="minecraft:guardian_attack_particle         "  # -守卫者攻击粒子(需要在水中才能显示)
ice_evaporation_emitter          ="minecraft:ice_evaporation_emitter          "  # -冰蒸发粒子
knockback_roar_particle          ="minecraft:knockback_roar_particle          "  # -击退震慑?粒子
magnesium_salts_emitter          ="minecraft:magnesium_salts_emitter          "  # -白色颗粒效果
mob_block_spawn_emitter          ="minecraft:mob_block_spawn_emitter          "  # -怪物砖激活粒子
mob_portal                       ="minecraft:mob_portal                       "  # -传送门粒子2(与之前不同)
mobspell_emitter                 ="minecraft:mobspell_emitter                 "  # -黑色颗粒效果
portal_directional               ="minecraft:portal_directional               "  # -传送门粒子3
silverfish_grief_emitter         ="minecraft:silverfish_grief_emitter         "  # -白色烟雾
splash_spell_emitter             ="minecraft:splash_spell_emitter             "  # -大型黑色颗粒效果
sponge_absorb_water_particle     ="minecraft:sponge_absorb_water_particle     "  # -气泡粒子5 (需要在水中才能显示)
squid_flee_particle              ="minecraft:squid_flee_particle              "  # -气泡粒子6 (需要在水中才能显示)
squid_ink_bubble                 ="minecraft:squid_ink_bubble                 "  # -小型蓝色气泡粒子(不明显)(需要在水中才能显示)
squid_move_particle              ="minecraft:squid_move_particle              "  # -蓝色气泡粒子(需要在水中才能显示)
stunned_emitter                  ="minecraft:stunned_emitter                  "  # -眩晕？粒子(必须退出存档才能清除)
totem_particle                   ="minecraft:totem_particle                   "  # -不死图腾触发粒子
water_evaporation_actor_emitter  ="minecraft:water_evaporation_actor_emitter  "  # -水蒸发粒子
water_evaporation_bucket_emitter ="minecraft:water_evaporation_bucket_emitter "  # -水蒸发粒子2
water_splash_particle            ="minecraft:water_splash_particle            "  # -水粒子
water_wake_particle              ="minecraft:water_wake_particle              "  # -向上水粒子
wither_boss_invulnerable         ="minecraft:wither_boss_invulnerable         "  # -凋灵粒子(向上)
underwater_torch_particle        ="minecraft:underwater_torch_particle        "  # -水下火把粒子(需要在水中才能显示)
note_particle                    ="minecraft:note_particle                    "  # -彩色音符粒子(无法正常显示)
conduit_absorb_particle          ="minecraft:conduit_absorb_particle          "  # -潮涌能量粒子2(无法正常显示)
redstone_wire_dust_particle      ="minecraft:redstone_wire_dust_particle      "  # -红石粒子
falling_dust_red_sand_particle   ="minecraft:falling_dust_red_sand_particle   "  # -红沙粒子
falling_dust                     ="minecraft:falling_dust                     "  # -掉落方块粒子?
falling_dust_sand_particle       ="minecraft:falling_dust_sand_particle       "  # -沙子粒子
heart_particle                   ="minecraft:heart_particle                   "  # -爱心❤️粒子
lab_table_heatblock_dust_particle="minecraft:lab_table_heatblock_dust_particle"  # -元素构造器粒子
mobflame_single                  ="minecraft:mobflame_single                  "  # -火焰🔥粒子
falling_border_dust_particle     ="minecraft:falling_border_dust_particle     "  # -类似于瞬间治疗粒子
lava_particle                    ="minecraft:lava_particle                    "  # -飞溅岩浆粒子
rain_splash_particle             ="minecraft:rain_splash_particle             "  # -雨点水花粒子
water_drip_particle              ="minecraft:water_drip_particle              "  # -水从天花板滴落粒子
